version: '2'
services:
  httpd:
    build: .
    ports:
      - 8080:80
    restart: always
  proxy:
    image: dperson/torproxy
    restart: always
    ports:
      - 8118:8118
      - 9050:9050
    environment:
      - 'LOCATION=RU'

